### ISSUE TITLE
Thorlabs OSA driver

### ISSUE THREAD

**Issue by kvoutyras** [DanHickstein/gracefulOSA#3]
Hello, I am wondering if there is the Thorlabs mid range OSA code available. I recently got an Thorlabs OSA20X and I cannot find any driver available... Looking forward to your feedback!

**Comment by DanHickstein** [comment]
Hi there! This repo is just some code that links various OSAs with a thorlabs rotation stage, so not general advice for how to use the Thorlabs OSAs. You'd need to ask Thorlabs for general advice about this.

That said, if you've installed the Thorlabs OSA software, then you should have the dll that you need living in `C:\\Program Files\\Thorlabs\\Thorlabs OSA\\FTSLib.dll`, or someplace similar.

Here is the code that we used to collect data with the OSA and automatically move a rotation stage, in case that's helpful for you:
https://gist.github.com/DanHickstein/c33a28cdb738602c04fdee1d4c44dc79
